### ISSUE TITLE
Bring to web and desktop platforms 

### ISSUE THREAD

**Issue by MOpenlander** [joafc96/place_picker_google#1]
Would be great if this could be used on both web and desktop platforms in addition to the mobile ones it already supports

**Comment by jtkeyva** [comment]
yes, my exact thoughts. this is a much needed package and web support would make it that much better and more useful

**Comment by joafc96** [comment]
Hi @MOpenlander @jtkeyva I have updated the package with web support. I won't be able to provide desktop support as [google_maps_flutter](https://pub.dev/packages/google_maps_flutter) currently does not support desktop apps. 
Please check  [0.0.7](https://pub.dev/packages/place_picker_google)

**Comment by joafc96** [comment]
Closing this as Web support is provided from [0.0.7](https://pub.dev/packages/place_picker_google) and [google_maps_flutter](https://pub.dev/packages/google_maps_flutter) does not support desktop apps.
