### ISSUE TITLE
Customize style

### ISSUE THREAD

**Issue by YSDC** [joafc96/place_picker_google#13]
Is there any plan to let us customize the style (color, font, etc.)? This would be really useful, I don't understand why we cannot do it in any place picker lib in Flutter...

**Comment by joafc96** [comment]
@YSDC Which styles are you referring to?

If it is regarding the TextField, please use `searchInputConfig` of type  `SearchInputConfig` and to update the TextField's decoration please use `searchInputDecorationConfig`  `SearchInputDecorationConfig` class.

If it is regarding the selected widget at the bottom, please use either 
-  selectedLocationNameStyle
- selectedFormattedAddressStyle
- selectedActionButtonChild

or if you want to add a custom selected widget, please use `selectedPlaceWidgetBuilder` of type `SelectedPlaceWidgetBuilder`

**Comment by YSDC** [comment]
Thanks it worked! It would be worth mentioning it in the Readme such that people know from pub.dev all the options you offer :)

**Comment by giorgio79** [comment]
I was just looking into how to make the colors of the inputs black like on the screenshot.

**Comment by joafc96** [comment]
Hi @giorgio79, Please set `fillColor` in  `SearchInputDecorationConfig` class to the color you prefer, if you don't provide a value the Theme canvasColor will be taken.

**Comment by giorgio79** [comment]
Could you pls share your ThemeData for the black buttons

ThemeData(
        canvasColor: Colors.black, // Set black canvas color
        // Inherit other theme properties from parent
        scaffoldBackgroundColor: Colors.white,
        appBarTheme: Theme.of(context).appBarTheme, // Preserve existing AppBar style
        floatingActionButtonTheme: Theme.of(context).floatingActionButtonTheme,
        colorScheme: Theme.of(context).colorScheme,
      ),

getting this

![Image](https://github.com/user-attachments/assets/c0a51062-2a79-46de-b2d8-a7103463249b)
PS I have a floating action button on this screen, will turn it off :D

**Comment by joafc96** [comment]
Hi @giorgio79, Please set fillColor in  SearchInputDecorationConfig class to the color you prefer.

**Comment by giorgio79** [comment]
Thx joafc96

**Comment by joafc96** [comment]
No problem @giorgio79
