### ISSUE TITLE
Example on iOS: Unnamed location

### ISSUE THREAD

**Issue by jtkeyva** [joafc96/place_picker_google#5]
I can pan around the map and I see *some nearby places but not a ton. Also, if I tap on one, it says Unnamed Location and doesn't bring up an info pop up window?

I see this console error:
-[GMSx_GIPPseudonymousIDStore initializeStorage]: Shared App Groups unavailable

Does that have anything to do with this?

**Comment by joafc96** [comment]
@jtkeyva Could you please provide a screen recording of the same.
