### ISSUE TITLE
Turn off Location selection on map?

### ISSUE THREAD

**Issue by tiltmaster** [joafc96/place_picker_google#6]
first off, thank you so much for this awesome package, I wanted to ask few questions:

1. Can we disable the Map location selection, meaning when i click on the map it doesnt change location OR just simply hide the map?
2. Is there a radius for nearby locations?

Would very much like to know if im missing something here.

Thanks!

**Comment by joafc96** [comment]
1. Currently the tap gesture is provided for selection.
2. The radius is set as 150 for nearby locations now. If you want I can expose a property to set the radius

**Comment by tiltmaster** [comment]
> 1. Currently the tap gesture is provided for selection.
> 2. The radius is set as 150 for nearby locations now. If you want I can expose a property to set the radius

So i take it its not possible to hide the map and only enable nearby locations? thinking of it like a feature of Snapchat when u show list of nearby locations.

**Comment by joafc96** [comment]
So you want to hide just the map and show nearby locations?

**Comment by tiltmaster** [comment]
> So you want to hide just the map and show nearby locations?

That would be Big as an optional feature with a desired Radius set, the map still shows (Or Not) but you cant click and change position and only shows you a limited number of Places based on radius. Thats how Snapchat for example is doing it.

**Comment by tiltmaster** [comment]
I could probably fork this over the weekend and do that change but If this is something you want to add in the package then i would not do that i guess.

**Comment by joafc96** [comment]
Ahh that's too much of a change for me right now lol. Sorry about that. 
Please fork the repo and the desired UI changes.

**Comment by tiltmaster** [comment]
> Ahh that's too much of a change for me right now lol. Sorry about that. Please fork the repo and the desired UI changes.

understandable, thanks.

**Comment by joafc96** [comment]
Closing as non issue.
