### ISSUE TITLE
Upgrade http and geolocator version

### ISSUE THREAD

**Issue by Safius-Sifat** [joafc96/place_picker_google#7]
Hello,  

Thank you for the great package; I'm really enjoying it. However, the outdated versions of the http and geolocator packages are causing dependency issues with my other packages.

Could you please upgrade these to more recent versions?

**Comment by joafc96** [comment]
@Safius-Sifat Don't worry, I will update all the dependencies to their latest versions.

**Comment by joafc96** [comment]
Closing the issue as it has been completed and is now available in version [0.0.11](https://pub.dev/packages/place_picker_google)
